apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: r104aizlo-java-quarkus 
  janus-idp.io/tekton: r104aizlo-java-quarkus
  backstage.io/kubernetes-id: r104aizlo-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r104aizlo-java-quarkus
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml